//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Space
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string description { get; set; }
        public int placeid { get; set; }
        public int price { get; set; }
        public int typeEventId { get; set; }
        public int userId { get; set; }
        public byte[] photo { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual TypeEvent TypeEvent { get; set; }
        public virtual User User { get; set; }
    }
}
